[package]
name = "html2json"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
html_parser = "0.7.0"
regex = "1.10.6"
serde_json = "1.0.122"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
